# Generated by Django 2.2.5 on 2019-09-27 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('unit_price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('status', models.CharField(choices=[('AVAILABLE', 'ITEM AVAILABLE'), ('SOLDOUT', 'ITEM SOLDOUT'), ('RESTOCKING', 'RESTOCKING IN FEW DAYS')], default='AVAILABLE', max_length=10)),
                ('issues', models.CharField(default='No Issues', max_length=50)),
            ],
        ),
    ]
