# Generated by Django 2.2.5 on 2019-09-30 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('quantity', models.IntegerField()),
                ('slug', models.SlugField()),
                ('active', models.BooleanField(default=True)),
                ('created', models.TimeField(auto_now_add=True)),
                ('updated', models.TimeField(auto_now=True)),
                ('status', models.CharField(choices=[('AVAILABLE', 'ITEM AVAILABLE'), ('SOLDOUT', 'ITEM SOLDOUT'), ('RESTOCKING', 'RESTOCKING IN FEW DAYS')], default='AVAILABLE', max_length=10)),
                ('issues', models.CharField(default='No Issues', max_length=50)),
            ],
        ),
    ]
